### ISSUE TITLE
Difference in Rho-dependent terminators predicted

### ISSUE THREAD

**Issue by sonal04** [MarcoDiSalvo90/RhoTermPredict#1]
Hi,

I used your code to predict Rho-dependent terminators on NC_000913.3 but got only 5993 terminators in contrast to what you have deposited in the supplementary files, also the co-ordinates differ for the palindromic regions. Can you please let me know what genomic sequences you used for your supplementary file. Thanks

**Comment by MarcoDiSalvo90** [comment]
I re-run the code and, obviously, I exactly obtained the same results reported in the paper and in its supplementary file. 

In my opinion, the possible causes of the different results obtained by you could be:

- a different input genomic sequence (but now you used the genome file I provided to you, i.e.the right complete genome of E. coli K12);
- some changes in the original code (the code you used is the same as the our in github or did you change anything in it?);
- Did you use the last release/version of RhoTermPredict code? (Maybe you did not use the most recent version of the code present in github, but a less recent version) 

Anyway, I advise you to update the python libraries used in the code (in the github repository there is the requirements.txt file containing all dependencies).
