### ISSUE TITLE
Additional python requirement

### ISSUE THREAD

**Issue by JFsanchezherrero** [MarcoDiSalvo90/RhoTermPredict#4]
Hi there

I guess there is a requirement missing in your requirement.txt file provided.

I wanted to use this software so I created a new python3 environment and do:

`pip install requirements.txt`

Then I try:

`python RhoTermPredict_algorithm.py`

> ImportError: No module named Bio

Bio is not the pip package name for Biopython (https://biopython.org/wiki/Download). Then, Biopython should be include it in your requirements file.

I confirm it by doing: 

`pip install biopython`

Then I successfully run different examples using RhoTermPredict.

**Configuration**:
Python 3.7.6
pip 19.2.3
biopython 1.77

**Comment by MarcoDiSalvo90** [comment]
Thank you for your reporting. I will make this change to the requirement file as soon as possible
