### ISSUE TITLE
rhotermpredict

### ISSUE THREAD

**Issue by samoudj** [MarcoDiSalvo90/RhoTermPredict#5]
Hello, 
I am trying to apply rhotermpredict on 16000 complete genomes. Can you tell me what is the command line that alllows me to execute rhotermpredict in one line like rhotermpredict_algorithm.py -i input.fasta -o output.csv ...??
please it is really important, i would appreciate if you can help me :)

**Comment by MarcoDiSalvo90** [comment]
Hi,

You only have to write in the command line "python RhoTermPredict_algorithm.py" from the directory in which the code is saved.  Then the program will ask you the path of the file in which you saved your genomes, that you will have to write.

**Comment by MarcoDiSalvo90** [comment]
anyway, in the next future, I could modify the code in order to pass the genome file in the command line

**Comment by samoudj** [comment]
Hello, thank you for you response. I modifed today. Just need to remplace
$file=input() by $file =arg[1]. Thank you anyway. Wish you a nice
continuation
